# Generated by Django 2.0.7 on 2019-04-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190410_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
